// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN3EvdImWRR1WiAVda-LjiLC0ocJR-s48',
    appId: '1:650643344763:web:5732a9947a4ffa610081de',
    messagingSenderId: '650643344763',
    projectId: 'flutterpensionregistration',
    authDomain: 'flutterpensionregistration.firebaseapp.com',
    storageBucket: 'flutterpensionregistration.firebasestorage.app',
    measurementId: 'G-95PC65Q7CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKX9HKgQfiaRMnOp-jS0EXU8qrkhnm6G0',
    appId: '1:650643344763:android:d475814918a44b2c0081de',
    messagingSenderId: '650643344763',
    projectId: 'flutterpensionregistration',
    storageBucket: 'flutterpensionregistration.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhvHQ4aPca0-AIRh01pUoneFH5pyUglGo',
    appId: '1:650643344763:ios:6a6b292ea22e28ca0081de',
    messagingSenderId: '650643344763',
    projectId: 'flutterpensionregistration',
    storageBucket: 'flutterpensionregistration.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhvHQ4aPca0-AIRh01pUoneFH5pyUglGo',
    appId: '1:650643344763:ios:6a6b292ea22e28ca0081de',
    messagingSenderId: '650643344763',
    projectId: 'flutterpensionregistration',
    storageBucket: 'flutterpensionregistration.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN3EvdImWRR1WiAVda-LjiLC0ocJR-s48',
    appId: '1:650643344763:web:381d2591aef633b80081de',
    messagingSenderId: '650643344763',
    projectId: 'flutterpensionregistration',
    authDomain: 'flutterpensionregistration.firebaseapp.com',
    storageBucket: 'flutterpensionregistration.firebasestorage.app',
    measurementId: 'G-HXC840258P',
  );
}
